import type { Meta, StoryObj } from '@storybook/react-vite';
import type { ReactNode } from 'react';

const headings = [['H1', 'fontSizeHeading1', 'lineHeightHeading1', '38 / 32 px', '46 / 40 px', 'Список товаров'], ['H2', 'fontSizeHeading2', 'lineHeightHeading2', '30 / 26 px', '38 / 34 px', 'Динамика основных метрик'], ['H3', 'fontSizeHeading3', 'lineHeightHeading3', '24 / 20 px', '32 / 28 px', 'Динамика основных метрик'], ['H4', 'fontSizeHeading4', 'lineHeightHeading4', '20 / 16 px', '28 / 24 px', 'Динамика основных метрик'], ['H5', 'fontSizeHeading5', 'lineHeightHeading5', '16 / 14 px', '24 / 22 px', 'Динамика основных метрик'], ['H6', 'fontSizeHeading6', 'lineHeightHeading6', '14 / 12 px', '22 / 20 px', 'Динамика основных метрик']] as const;
const texts = [['Text SM', 'fontSizeSM', 'lineHeightSM', '12 / 10 px', '20 / 18 px', 'ps-8', 'ls-4'], ['Text Base', 'fontSize', 'lineHeight', '14 / 12 px', '22 / 20 px', 'ps-12', 'ls-8'], ['Text LG', 'fontSizeLG', 'lineHeightLG', '16 / 14 px', '24 / 22 px', 'ps-12', 'ls-8']] as const;
const cssVars: Record<string, string> = { fontSizeHeading1: '--argus-font-size-h1', fontSizeHeading2: '--argus-font-size-h2', fontSizeHeading3: '--argus-font-size-h3', fontSizeHeading4: '--argus-font-size-h4', fontSizeHeading5: '--argus-font-size-h5', fontSizeHeading6: '--argus-font-size-h6', lineHeightHeading1: '--argus-line-height-h1', lineHeightHeading2: '--argus-line-height-h2', lineHeightHeading3: '--argus-line-height-h3', lineHeightHeading4: '--argus-line-height-h4', lineHeightHeading5: '--argus-line-height-h5', lineHeightHeading6: '--argus-line-height-h6', fontSizeSM: '--argus-font-size-sm', fontSize: '--argus-font-size', fontSizeLG: '--argus-font-size-lg', lineHeightSM: '--argus-line-height-sm', lineHeight: '--argus-line-height-base', lineHeightLG: '--argus-line-height-lg' };
const Chip = ({ children }: { children: ReactNode }) => <span className="token-chip">{children}</span>;
function Typography() { return <main className="foundation-page"><div className="foundation-eyebrow">Foundation</div><h1 className="foundation-title">Typography</h1><p className="foundation-copy">Актуальная сетка токенов NEW DS ARGUS. Значения приводятся как Default / Compact; шрифт во всех стилях — X5 Sans VF.</p><section className="catalog-section"><h2>Heading</h2><table className="token-table"><thead><tr><th>Style</th><th>Использование</th><th>Font Family Token</th><th>Font Size Token</th><th>Line Height Token</th><th>Font Weight Token</th></tr></thead><tbody>{headings.map(([name, sizeToken, lineToken, size, line, sample]) => <tr key={name}><td>{name}</td><td>Заголовок</td><td><Chip>fontFamily · X5 Sans VF</Chip></td><td><Chip>{sizeToken} · {size}</Chip></td><td><Chip>{lineToken} · {line}</Chip></td><td><Chip>fontWeightStrong · 600</Chip></td></tr>)}</tbody></table><div className="type-scale">{headings.map(([name, sizeToken, lineToken, , , sample]) => <div className="typography-sample" key={`${name}-sample`}><div style={{ fontSize: `var(${cssVars[sizeToken]})`, lineHeight: `var(${cssVars[lineToken]})`, fontWeight: 'var(--argus-font-weight-strong)' }}>{sample}</div><div className="type-meta"><Chip>{sizeToken}</Chip><Chip>{lineToken}</Chip><Chip>fontWeightStrong</Chip></div></div>)}</div></section><section className="catalog-section"><h2>Paragraph Text</h2><table className="token-table"><thead><tr><th>Style</th><th>Использование</th><th>Размер и интерлиньяж</th><th>Отступы</th></tr></thead><tbody>{texts.map(([name, sizeToken, lineToken, size, line, paragraph, list]) => <tr key={name}><td>{name}</td><td>{name === 'Text SM' ? 'Мелкий текст' : name === 'Text Base' ? 'Обычный текст' : 'Увеличенный текст'}</td><td><Chip>{sizeToken} · {size}</Chip><Chip>{lineToken} · {line}</Chip></td><td><Chip>{paragraph}</Chip><Chip>{list}</Chip></td></tr>)}</tbody></table></section><section className="catalog-section"><h2>UI Text</h2><p className="foundation-copy">UI Text использует те же размеры X5 Sans VF, но применяется в контролах, таблицах и служебных надписях. При переключении «Размерность» все значения меняются по токенам.</p></section></main>; }
export default { title: 'Foundation/Typography', component: Typography, parameters: { controls: { disable: true } } } satisfies Meta<typeof Typography>;
export const Scale: StoryObj<typeof Typography> = { name: 'Токены и стили' };
