import type { Meta, StoryObj } from '@storybook/react-vite';
import { Check, Field, Radio, Select, Switch, TextArea, TextInput } from './FormControls';

function Forms() { return <div className="argus-form-grid"><Field label="Название" hint="До 120 символов" required><TextInput placeholder="Введите название" /></Field><Field label="Статус"><Select defaultValue="draft"><option value="draft">Черновик</option><option value="active">Активна</option><option value="closed">Закрыта</option></Select></Field><Field label="Описание" error="Заполните обязательное поле"><TextArea invalid placeholder="Опишите задачу" /></Field><div><Check defaultChecked>Показывать в общем списке</Check><div style={{ height: 12 }} /><Check disabled>Недоступный выбор</Check></div><div style={{ display: 'grid', gap: 8 }}><Radio name="scope" value="all" defaultChecked>Все пользователи</Radio><Radio name="scope" value="role">По роли</Radio></div><Switch defaultChecked label="Получать уведомления" /></div>; }
export default { title: 'Components/Form controls', component: Forms, parameters: { layout: 'padded' } } satisfies Meta<typeof Forms>;
export const Interactive: StoryObj<typeof Forms> = {};
export const TextFields: StoryObj<typeof Forms> = { render: () => <div className="argus-form-grid"><Field label="Название" hint="До 120 символов" required><TextInput placeholder="Введите название" /></Field><Field label="Описание" error="Заполните обязательное поле"><TextArea invalid placeholder="Опишите задачу" /></Field></div> };
export const SelectControl: StoryObj<typeof Forms> = { render: () => <div style={{ maxWidth: 320 }}><Field label="Статус"><Select defaultValue="draft"><option value="draft">Черновик</option><option value="active">Активна</option><option value="closed">Закрыта</option></Select></Field></div> };
export const Checkboxes: StoryObj<typeof Forms> = { render: () => <div style={{ display: 'grid', gap: 12 }}><Check defaultChecked>Показывать в общем списке</Check><Check>Не выбрано</Check><Check disabled>Недоступный выбор</Check></div> };
export const RadioGroup: StoryObj<typeof Forms> = { render: () => <div style={{ display: 'grid', gap: 10 }}><Radio name="access" value="all" defaultChecked>Все пользователи</Radio><Radio name="access" value="role">По роли</Radio><Radio name="access" value="private">Только я</Radio></div> };
export const SwitchControl: StoryObj<typeof Forms> = { render: () => <div style={{ display: 'grid', gap: 12 }}><Switch defaultChecked label="Получать уведомления" /><Switch label="Публичная задача" /></div> };
